services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    volumes:
      - ./images:/app/images  

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  mongodb:
    image: "mongo:6.0"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=ImageDatabase

volumes:
  mongo-data: