version: "3.9"

services:
  kafka:
    build:
      context: ./Kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
      - "9999:9999"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://host.docker.internal:9094"
    volumes:
      - kafka_data:/opt/kafka/data
    networks:
      - mynetwork
    
  api_gateway:
    build:
      context: ./ApiGateway/ApiGateway
    container_name: api_gateway
    depends_on:
      - kafka
      - mongo-init
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      ConnectionStringsMongoDB: "mongodb://mongo-primary:27017,mongo-secondary1:27017,mongo-secondary2:27017/?replicaSet=rs0"
    ports:
      - 50051:8080
    networks:
      - mynetwork

  resizer_image:
    build:
      context: ./ResizeImageMicroservice/ResizeImageMicroservice
    container_name: resizer_image
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
      - 50052:8080
    networks:
      - mynetwork

  rotator_image:
    build:
      context: ./ImageRotationMicroservice/ImageRotationMicroservice
    container_name: rotator_image
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
      - 50053:8080
    networks:
      - mynetwork

  message_router:
    build:
      context: ./MessageRouter/MessageRouter
    container_name: message_router
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    ports:
      - 50054:8080
    networks:
      - mynetwork

  mongo-primary:
    image: mongo:4.4
    container_name: mongo-primary
    restart: always
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo-primary_data:/data/db
    networks:
      - mynetwork

  mongo-secondary1:
    image: mongo:4.4
    container_name: mongo-secondary1
    restart: always
    ports:
      - "27018:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo-secondary1_data:/data/db
    networks:
      - mynetwork

  mongo-secondary2:
    image: mongo:4.4
    container_name: mongo-secondary2
    restart: always
    ports:
      - "27019:27017"
    command: mongod --replSet rs0 --bind_ip_all
    volumes:
      - mongo-secondary2_data:/data/db
    networks:
      - mynetwork

  mongo-init:
    image: mongo:4.4
    depends_on:
      - mongo-primary
      - mongo-secondary1
      - mongo-secondary2
    volumes:
      - ./MongoInit/init.sh:/init.sh
      - mongo_init_data:/initdb
    entrypoint: [ "bash", "/init.sh" ]
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    
volumes:
  kafka_data:
  mongo-primary_data:
  mongo-secondary1_data:
  mongo-secondary2_data:
  mongo_init_data:
